language: node_js
node_js:
- '8.10'

cache:
  yarn: true
  directories:
  - node_modules

script: yarn test:ci

before_deploy:
- yarn build
- cd dist

deploy:
  provider: npm
  email: benjamin.otto@style-systems.de
  skip_cleanup: true
  api_key:
    secure: AphAJLLUxzULpmtIjEn0KTd3N4nxIK6aG3Jj23RsQvVAAcHzB2HXNJ9oKiKSQmXEbe9PkXLq5SIhXBJ/ukvFTlFJoJnxcTeV3ds0H8Lyq1yhV3L7HKFpFHqil7fxlCUTLGXYn++uUMRZCM4RXAd7qczqz/fGng63Q4dC2tVv6N7MXL7BedK6QGBjU2NkmMKdOlbQd1rZFoAc89oy1QJKFYo7CvMj+IKRPkfrr4EI7tQa4Pw5eNlyuIayFb4+oJnnwPlTg/+0wKzlMIVOZT2GH0CLUHXVsL/6LqgDtj/s+R6RW99HUUo+n9ZhYRi8ISakdyN3pFbkV13EWd2tA36C7tNZckLUjtXb3DDBs2NSr26uiiV4WRj8lHc155shpEimKTkkN1ibBsgEUnJ3KYBFkCXtacsdoGewn8PdvzQ5HP7qIB5eqBNteU3hD7FYByIpt/o20JWbmbIOtz/NazoOdMU1C+li98yK/U0JvlhdNezZVVkROmHgVR9Y86FoSp5HZ/cum8vfxY379yDDUE3arextvaJAYWS19QzPSgGGtVhJ9CaGewBqaEgXCfHCxVjGwrToF/Y0zgz0rztQV/AVdSqY30Fv2+sxmEjXNZw2zKxFvfEIeEXTR7q908YeBMqnxR5a+jrt7L4UOqKBHBo3UPxB5sfT3i9xGvQWMaM5+wU=
  on:
    tags: true
    repo: otbe/schnipp
